[WIP] Add a flag to switch where to get the data needed for the scheduled job
screwdriver-cd/queue-service pull request #60
Opened 2022-12-02 10:17 UTC by yk634

## Context

Change following https://github.com/screwdriver-cd/queue-service/pull/58.
The change to not use `periodicBuildConfigs` has a large impact and should be selectable by a feature flag.

## Objective

Add the setting `periodicBuildTableEnabled` to allow control over whether or not `periodicBuildConfigs` are used.

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-12-03 01:05 UTC, DekusDenial requested changes
other than that one comment, else LGTM

2022-12-03 01:05 UTC, DekusDenial commented on plugins/queue/scheduler.js
> +    if (triggerBuild && (periodicBuildTableEnabled || !job.archived)) {
```suggestion
    if (triggerBuild && !job.archived) {
```
what it was is fine for checking archived job and is not really related to `periodicBuildTable`

2022-12-05 01:19 UTC, y-oksaku commented on config/custom-environment-variables.yaml
> +    # whether or not to retrieve from redis that the data needed to start periodic builds
Indentation looks off.

2022-12-05 01:19 UTC, y-oksaku commented on plugins/queue/scheduler.js
> +    return Promise;
```suggestion
    return Promise.resolve();
```

2022-12-05 01:38 UTC, y-oksaku approved these changes

2022-12-05 02:09 UTC, ibu1224 approved these changes

2022-12-05 03:15 UTC, DekusDenial approved these changes

2022-12-05 03:15 UTC, merged